// Code generated by ent, DO NOT EDIT.

package epic

const (
	// Label holds the string label denoting the epic type in the database.
	Label = "epic"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the epic in the database.
	Table = "epics"
)

// Columns holds all SQL columns for epic fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
