package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"

	"github.com/jenmud/consensus/graph/generated"
	"github.com/jenmud/consensus/graph/model"
)

// Events is the resolver for the events field.
func (r *subscriptionResolver) Events(ctx context.Context, topic *string) (<-chan *model.Event, error) {
	panic(fmt.Errorf("not implemented: Events - events"))
}

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
